# err_raise.py
class data_error(ValueError):
    pass
